#!/usr/bin/env bash

NAME=${NAME:-etcd2-bootstrapper}

pushd `dirname $0` > /dev/null
ROOTPATH=`pwd -P`
popd > /dev/null

mkdir -p $ROOTPATH/bin
cd $ROOTPATH/src/github.com/glerchundi/etcd2-bootstrapper

#GOPATH=$ROOTPATH/vendor:$ROOTPATH \
#CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 \
#  go build -o $ROOTPATH/bin/${NAME}-darwin-amd64 -a -tags netgo -installsuffix cgo -ldflags '-extld ld -extldflags -static' -a -x .

GOPATH=$ROOTPATH/vendor:$ROOTPATH \
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
  go build -o $ROOTPATH/bin/${NAME}-linux-amd64 -a -tags netgo -installsuffix cgo -ldflags '-extld ld -extldflags -static' -a -x .


